# Generated by Django 4.1.2 on 2024-04-27 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_product_name_product_brand_product_color_and_more'),
        ('shop', '0003_remove_customer_address_cart_cartaddress_and_more'),
    ]

    operations = [
    ]
