# Generated by Django 4.1.2 on 2024-04-27 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_name_alter_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='cartAddress',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customerAddress',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='customUseraddress',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('Nike', 'Nike'), ('Adidas', 'Adidas'), ('Reebok', 'Reebok'), ('Converse', 'Converse')], default='', max_length=20),
        ),
    ]
